### ISSUE TITLE
Schedule does not respect DST

### ISSUE THREAD

**Issue by dipth** [activesphere/exq-scheduler#16]
I have the following config:

```
config :exq_scheduler,
  time_zone: "Europe/Copenhagen"

config :exq_scheduler, :schedules,
  generate_new_game: %{
    description: "Example",
    cron: "0 0 * * *",
    class: "MayApp.NightlyWorker",
    queue: "example",
    retry: false
  }
```

I would expect that to enqueue the `NightlyWorker` job at midnight local time (Copenhagen). However looking in my server log, it appears that the job was scheduled an hour late at 1 in the night instead:

```
Apr 07 01:00:00.086am info app web.1 Enqueued a job class: "MayApp.NightlyWorker" queue: "example" enqueued_at: 1554591600 args: []
```

So it appears that the schedule does not respect daylight savings, which started in Denmark on the night between March 30 and 31.

Here are my dependencies:

```
...
{:exq, "~> 0.13.2"},
{:exq_ui, "~> 0.10.0"},
{:exq_scheduler, "~> 0.6.2"},
{:tzdata, "~> 1.0.0-rc.1", override: true}
```

Notice that I've forcefully included the latest version of tzdata in hopes that this would solve the issue, since the previous version had trouble downloading the latest timezone database.

**Comment by ananthakumaran** [comment]
This is a known issue. We have discussed this, but haven't spent any time to solve it.
