### ISSUE TITLE
compatibility with Timex > 3.3

### ISSUE THREAD

**Issue by alexandremcosta** [activesphere/exq-scheduler#20]
Hi, thanks for your great work!

Do you have plans for supporting Timex latest version? If not, please update mix.exs
```
{:timex, "~> 3.3.0"}
```

The problem is in https://github.com/activesphere/exq-scheduler/blob/6114c10ce659f5a7a6af8cc501992d00eb1678e6/lib/exq_scheduler/schedule.ex#L148.

Problems:
- Since 3.4, `Timex.resolve/3` doesn't support passing an erlang representation of the date
- This method now returns TimezoneInfo and AmbiguousTimezoneInfo structs instead of Datetime and AmbiguousDatetime

I attempted to solve by myself, but no success :(

**Comment by ananthakumaran** [comment]
Thanks for reporting the issue. I have added version constraint for now. Let's keep this issue open till we come up with a proper fix.

**Comment by ananthakumaran** [comment]
fixed by https://github.com/activesphere/exq-scheduler/pull/31
