### ISSUE TITLE
`/exq/recurring` page returns Internal Server Error

### ISSUE THREAD

**Issue by overture8** [activesphere/exq-scheduler#40]
I get an intermittent issue on production where the `/exq/recurring` page returns Internal Server Error. When this is happening, the related scheduled jobs are not processing. The only way to fix it is to restart the phoenix server.

I can’t figure out what is happening or how to get to the bottom of it. Does anyone have an idea of what might be going on?

**Comment by ananthakumaran** [comment]
Could you post the error message

**Comment by overture8** [comment]
Sorry - I think it’s fixed now. The issue was that my logging package was erroring quite frequently and it must have been hitting the upper limit of errors for an Elixir app, which caused it to crash the app. When it restarted the app at the root level it must not have restarted exq-scheduler.
